---
- name: Node.js
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  vars_prompt:
    - name: 'mysql_selection'
      prompt: "\nPlease choose the number for MySQL version [ 1/2/3/4] \n\n
      1: MySQL5.5(only for CentOS7.x, AmazonLinux)\n
      2: MySQL5.6(only for CentOS7.x, AmazonLinux, Ubuntu16.04 )\n
      3: MySQL5.7\n
      4: MySQL8.0\n"
      private: no
      default: 3

    - name: 'mongodb_selection'
      prompt: "\nPlease choose the number for MongoDB version [ 1/2/3/4] \n\n
      1: MongoDB3.0\n
      2: MongoDB3.2\n
      3: MongoDB3.4\n
      4: MongoDB3.6\n
      5: MongoDB4.0\n"
      private: no
      default: 4

    - name: 'nodejs_selection'
      prompt: "\nPlease choose the number for MongoDB version [ 1/2/3/4] \n\n
      1: NodeJS 10.x\n
      2: NodeJS 12.x\n
      3: NodeJS 13.x\n"
      private: no
      default: 2

  vars:
    mysql_select:
      '1': '5.5'
      '2': '5.6'
      '3': '5.7'
      '4': '8.0'
    mysql_version: "{{mysql_select[mysql_selection]}}" 

    mongodb_select:
      '1': '3.0'
      '2': '3.2'
      '3': '3.4'
      '4': '3.6'
      '5': '4.0'
    mongodb_version: "{{mongodb_select[mongodb_selection]}}" 

    nodejs_select:
      '1': '10'
      '2': '12'
      '3': '13'
    nodejs_version: "{{nodejs_select[nodejs_selection]}}" 

  roles:
  - { role: role_common , tags: "role_common"} 
  - { role: role_nodejs , tags: "role_nodejs"} 
  - { role: role_nginx , tags: "role_nginx"} 
  - { role: role_mysql , tags: "role_mysql"}
  - { role: role_mongodb , tags: "role_mongodb"}
  - { role: role_mongodb , tags: "role_express"}
  - { role: role_docker , tags: "role_docker"} 
  - { role: role_redis , tags: "role_redis"}
  - { role: role_init_password , tags: "role_init_password"} 
  - { role: role_preend , tags: "role_preend"} 
  - { role: role_end , tags: "role_end"} 
